# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: improvedchickadee
service: blog-sentiment-app

provider:
  name: aws
  runtime: python3.10
  region: us-east-1
  ecr:
    images:
      blog-api:
        uri: 360367874658.dkr.ecr.us-east-1.amazonaws.com/serverless-blog-sentiment-app-dev:1740684472

functions:
  app:
    name: blog-sentiment-app-v2
    # image:
    #   name: blog-api
    handler: app.main.handler
    events:
      - httpApi:
          path: /
          method: GET
      - httpApi:
          path: /posts
          method: GET
      - httpApi:
          path: /post
          method: POST
      - httpApi:
          path: /post/{post_id}
          method: PATCH
      - httpApi:
          path: /post/{post_id}
          method: DELETE
      - httpApi:
          path: /post/restore/{post_id}
          method: PATCH
      - httpApi:
          path: /comment/{post_id}
          method: POST
      - httpApi:
          path: /comment/{post_id}
          method: GET
      - httpApi:
          path: /comment/{post_id}/{comment_id}
          method: PATCH
      - httpApi:
          path: /comment/{post_id}/{comment_id}
          method: DELETE
      - httpApi:
          path: /sentiment/{post_id}
          method: POST
      - httpApi:
          path: /sentiment/{post_id}/{sentiment_id}
          method: PATCH

resources:
  Resources:
    BlogAppTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: BlogAppTable
        BillingMode: PAY_PER_REQUEST

        AttributeDefinitions:
          - AttributeName: PK
            AttributeType: S
          - AttributeName: SK
            AttributeType: S
          - AttributeName: GSI1PK
            AttributeType: S
          - AttributeName: GSI1SK
            AttributeType: S
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
          - AttributeName: SK
            KeyType: RANGE

        GlobalSecondaryIndexes:
          - IndexName: GSI1
            KeySchema:
              - AttributeName: GSI1PK
                KeyType: HASH
              - AttributeName: GSI1SK
                KeyType: RANGE
            Projection:
              ProjectionType: ALL

        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES

plugins:
  - serverless-offline
